### ISSUE TITLE
Less middleware doesn't allow to import URLs

### ISSUE THREAD

**Issue by kaddaSz** [SAP/connect-openui5#14]
We have a use case where we import the global and base less files from UI5 from an external source (e.g. HCP).
Less itself allows such an scenario and can read from this source. 
Unfortunately the less middleware raises an error after the results are already compiled.

In file less.js line 69 all imports are again accessed with fs.stat. For a Url this fails.
If I remove the evaluation of "statErr", the less middleware works fine.

**Comment by matz3** [comment]
Although our concept of themes is based on relative paths only (to be independent of the surrounding environment), this sounds valid.
I did not expect URLs to be part of imports, so that's why there is no special handling, yet.

A fix would be to check for such imports and skip the `fs.stat`.
Regarding cache invalidation the simple solution would be to not cache at all if URLs are used.
The better (but more complex) one would be to add caching on HTTP level ("Last-Modified" header, etc.) 

Feel free to submit a PR.

**Comment by matz3** [comment]
Our current scope doesn't include importing from URLs, and from our side there's no plan to support this.
